---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.imageRegistries.name }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageRegistries.url (printf "%s:%s" .Values.imageRegistries.username .Values.imageRegistries.password | b64enc) | b64enc }}
